### ISSUE TITLE
The python mode error

### ISSUE THREAD

**Issue by YuanPre** [purcell/emacs.d#427]
Hello Purcell:
I recently learned python, but in your configuration, the python mode doesn't work:
environment:
```
Arch Linux x86_64 All software has been updated to the latest ;
Emacs 25.1.1 & your configuration latest version ;
Packages about python in system:

python 3.6.0-2
python-gobject 3.22.0-2
python2 2.7.13-1
```
When I open the python file, it will output error log:
```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'setuptools'
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'setuptools'
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'setuptools'
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'setuptools'
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'setuptools'
```
It looks like some modules are missing, but I don't know anything about python.
So, I don't know what to install.
Please guide me, thank you.

And……sorry for my English.
I will only speak English in Google translation......

**Comment by purcell** [comment]
It looks like your python environment does not have the `setuptools` package. It's needed by `anaconda`, which provides extended support for Python in this config.

See [here](https://github.com/Homebrew/homebrew-core/issues/3078#issuecomment-233989229) or [here](https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources) for things you can try.

Alternatively, you can disable the extended Python support by commenting out or deleting [this code in the config](https://github.com/purcell/emacs.d/blob/04b00d6e7e31dd68ec5628d08bc41af7dabedaf0/lisp/init-python-mode.el#L8-L15).

**Comment by YuanPre** [comment]
Thank you very much! I refer to the [Arch Wiki ](https://wiki.archlinux.org) about Python.
 Then,I installed `ipython` in my system to fill the missing module. Then, It works.

**Comment by purcell** [comment]
Great - glad you got it working!
