### ISSUE TITLE
Flycheck message with rubocop 

### ISSUE THREAD

**Issue by crazyrunsnail** [purcell/emacs.d#513]
Hi ,
When I open a ruby file ,the  the message show `*message*` buffer :
```
Suspicious state from syntax checker ruby-rubocop: Flycheck checker ruby-rubocop returned non-zero exit code 1, but its output contained no errors: /Users/Rounds/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems.rb:291:in 'find_spec_for_exe': can't find gem rubocop (>= 0.a) with executable rubocop (Gem::GemNotFoundException)
	from /Users/Rounds/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems.rb:310:in 'activate_bin_path'
	from /Users/Rounds/.rvm/gems/ruby-2.4.0/bin/rubocop:23:in '<main>'
	from /Users/Rounds/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Rounds/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
 ```
I'm a newer to emacs and ruby .
But `rubocop` can run perfect when I use Console.

**Comment by purcell** [comment]
You're using `rvm`, it seems, so you might want to install and use the [rvm package](https://github.com/senny/rvm.el).
